### PR TITLE
♻️ Throw Error instead of Message

### PR DESCRIPTION
**Pull request by skick1234**
Throw `Error` instead of `Message` if `Player` does not have any listeners registered for the `error` event.

### CODE REVIEW

**Review by Snowflake107 — APPROVED** [review]

**Comment by chroventer** [comment]
You just switched the place of the parameters of the error event and that's it.

**Comment by Snowflake107** [comment]
He is trying to 
```js
.on("error", (error, message)
```

instead of 
```js
.on("error", (message, error)
```
imo

**Comment by skick1234** [comment]
> You just switched the place of the parameters of the error event and that's it.

If `message` is the second parameter and `Player` doesn't have any listeners registered for the `error` event, it will throw `message` as `Unhandled error` instead of `error`.

**Comment by Androz2091** [comment]
Yes, indeed

**Review by Androz2091 — APPROVED** [review]
Thank you

**Pull request merged**
