### PR TITLE
dev updates

### PR DESCRIPTION
**Pull request by DevAndromeda**
## Changes
- feat(Queue): add `onBeforeCreateStream` to `Queue` instance and queue init options
-  fix(VoiceConnection): handle voice connection destroy error (#789)
- fix(Track): fix toJSON causing errors (https://github.com/Androz2091/discord-player/pull/806/commits/ad9212c0e92bdb50a59036de30473386dc568072)
- feat(Queue): add `skipTo` method (https://github.com/Androz2091/discord-player/pull/806/commits/751ce122bc29a8c19d0256b52759b73d77997229)
- fix(Queue): watch destroyed state for insert method (https://github.com/Androz2091/discord-player/pull/806/commits/1c9a00bf1a72bea45748990e57f9aafaa72a6b5e)
- feat(Queue): add `spotifyBridge` option (edb517c8c6499e81b9dcbbb346126492b4679ed3)
- feat(Queue): add `disableVolume` option (87d49c688d70d7035166fce429e41e72a6fa632c)
- feat(Queue): handle error events by default (31855578335d2d3070faaaf53c866321a632603b)

# Queue.onBeforeCreateStream
This method traps the stream downloader. This is not related to extractors api though, since it can bypass those. This could also be used to block certain source like `youtube`. You can disable `spotifyBridge` to block `spotify<->youtube` bridge.

> Note: this method may not work properly if `spotifyBridge` is enabled.

```js
const playdl = require("play-dl");

// other code
const queue = player.createQueue(..., {
    ...,,
    spotifyBridge: false, // set this to true if you need spotify<->youtube bridge.
    // setting the bridge to true (which is set to true by default) sets the source to "youtube" for onBeforeCreateStream
    async onBeforeCreateStream(track, source, _queue) {
        // only trap youtube source
        if (source === "youtube") {
            // track here would be youtube track
            return (await playdl.stream(track.url)).stream;
            // we must return readable stream or void (returning void means telling discord-player to look for default extractor)
        } else if (source === "spotify") { // trap spotify
            // resolve spotify stream here
        }
    }
});

```

## Status

- [x] These changes have been tested and formatted properly.

### CODE REVIEW

**Comment by stefnotch** [comment]
Just tried this out with `"play-dl": "^1.0.3"` and Typescript. The code is as follows

```js
const queue = player.createQueue(guild, {
      leaveOnEnd: false,
      leaveOnStop: true,
      leaveOnEmpty: true,
      leaveOnEmptyCooldown: 1,
      async onBeforeCreateStream(track, source, _queue) {
        // only trap youtube source
        if (source === "youtube") {
          // track here would be youtube track
          return (await playdl.stream(track.url)).stream;
          // we must return readable stream or void (returning void means telling discord-player to look for default extractor)
        }
      },
    });
```

`.stream` returns a PassThrough (from Node.js)
image

Meanwhile `onBeforeCreateStream` expects a `Readable`. Thus, Typescript ends up throwing an error.
image

Any chance you could take a look at this? Would be super appreciated!

**Comment by DevAndromeda** [comment]
can you try typecasting? `stream as Readable` (if that didn't work `stream as unknown as Readable`)? @stefnotch

**Comment by stefnotch** [comment]
This type cast does indeed work. However, apparently the type definitions don't accept undefined.

image

After tweaking the type definitions to accept it, this works perfectly. I'm not sure if the `as Readable` is even needed anymore.
image

**Comment by DevAndromeda** [comment]
> This type cast does indeed work. However, apparently the type definitions don't accept undefined.
> 
> image
> 
> After tweaking the type definitions to accept it, this works perfectly. I'm not sure if the `as Readable` is even needed anymore. image

thank you for the information

**Comment by Andy1210** [comment]
with onBeforeCreateStream the spotify source is broken
image
apparently youtube is hardcoded there, also if onBeforeCreateStream is a function, then customDownloader is true, so it will never run to the else branch, but in case we are returning void or null from the onBeforeCreateStream then we should run to the else branch.
I made a PR https://github.com/Androz2091/discord-player/pull/828 with my fix. I am not 100% sure if it's fine but it seems to be working.

**Pull request merged**
