### PR TITLE
✏️ discord.js v14 support

### PR DESCRIPTION
**Pull request by DevAndromeda**
## Changes

* No major api changes. Old codes depending upon discord-player v5 should work just fine.
* fixed `channelEmpty`
* better `initialVolume` setter
* other miscellaneous changes

### CODE REVIEW

**Comment by apenasigordev** [comment]
I tried change now. And something is happening.
Bot can't find any songs.

**Comment by DevAndromeda** [comment]
This update is now available on `npm i discord-player@5.3.0-dev.0`

**Review by Androz2091 — COMMENTED** [review]
Could we keep examples? They're very useful when building a bot with the lib 
otherwise seems great, going to be tested asap!

**Comment by DevAndromeda** [comment]
> Could we keep examples? They're very useful when building a bot with the lib otherwise seems great, going to be tested asap!

I used the `discord-music-bot` of yours to test this, how about using that?

**Comment by pwnker** [comment]
Looks awesome, would love to see this merged.

**Comment by pwnker** [comment]
When testing this `trackStart` does not fire for me.

**Comment by pwnker** [comment]
`trackStart` does not always fire for me from the testing I have done.

**Comment by DevAndromeda** [comment]
I will look into this

**Comment by pwnker** [comment]
> I will look into this

It seems to only happen some of the time and no errors of course, see if you can reproduce by restarting a few times and searching for songs.

**Comment by pwnker** [comment]
Looks like its only an issue if you don't remove the bot from your channel after a restart, so I think this is actually a non issue.

**Comment by DevAndromeda** [comment]
Landed some updates in `discord-player@5.3.0-dev.2`

**Comment by Bibyyy** [comment]
> I tried change now. And something is happening. Bot can't find any songs.

hey, I had errors with an old version I updated to the latest version and the same thing happens to me, what can I do? My bot can't find sound via QueryType.AUTO whether it's a link or something...

**Comment by CraftingShadowDE** [comment]
> > I tried change now. And something is happening. Bot can't find any songs.
> 
> hey, I had errors with an old version I updated to the latest version and the same thing happens to me, what can I do? My bot can't find sound via QueryType.AUTO whether it's a link or something...

This is a ytdl-core issue, discord-player can't do anything about it

**Pull request merged**
