### PR TITLE
✨ Support for Spotify playlists and albums

### PR DESCRIPTION
**Pull request by ThaddeusKKR**
I tested this on my bot, it's working so far.

Merging this can close #65 and #66.

### CODE REVIEW

**Review by ToledoSDL — APPROVED** [review]

**Comment by ThaddeusKKR** [comment]
By the way, this works well unless the playlist or album added has a lot of songs. In that case, adding these tracks to queue would take a while. I would suggest maybe an event named 'processingPlaylist' that is emitted when the playlist starts processing so that the user actually knows that their command went through and wait for the bot.

**Comment by imLinguin** [comment]
I think that fetching the entire playlist isn't a good idea especially when there are lots of songs. Better way whould be fetching song directly before playing it.

**Comment by LePtitMetalleux** [comment]
> I think that fetching the entire playlist isn't a good idea especially when there are lots of songs. Better way whould be fetching song directly before playing it. 

It would be in conflict with servers' queue

**Review by Androz2091 — APPROVED** [review]
Thank you, it works perfectly. It takes ~1 minute to fetch a playlist (50 songs), but I don't see any other solution for the moment (as we need the titles and the YT links to show the queue)

**Pull request merged**
