### PR TITLE
Start with zero.

### PR DESCRIPTION
**Pull request by hands8142**

### CODE REVIEW

**Comment by sabyr-cpu** [comment]
Why?

**Comment by hands8142** [comment]
If you find music, you start with zero. However, if you try to play, 0 is 1 and 1 is 2 must be entered.

**Comment by Androz2091** [comment]
Hello,
Did you actually test this PR before submitting it? 🤔 
Because as you can see here:
https://github.com/Androz2091/discord-player/blob/develop/src/Player.js#L206
It parses the message content (for example `1`), and then adds -1 (= 0, the index of the element in the array).

**Comment by hands8142** [comment]
I changed what starts with zero in the embed.

**Comment by Androz2091** [comment]
It's better if it starts at 1. Not everyone is a developer and people say "1st song" not "Song Zero".

**Comment by hands8142** [comment]
I'm sorry about that.

**Comment by Androz2091** [comment]
No problem, thank you anyway 👍

**Pull request closed without merging**
