### PR TITLE
Update Player.js | Add lyrics

### LINKED ISSUE #317: Add lyrics support
Add lyrics support for a lyrics command

### PR DESCRIPTION
**Pull request by jameslinimk**
- [x] Test
- [x] Add API key support

Closes #317

### CODE REVIEW

**Review by Snowflake107 — CHANGES_REQUESTED** [review]
You should add custom query support too. Also, I don't think you'd need to `resolve(undefined)`... `resolve()` should resolve `undefined` by default no? 🤔 Also, I see you are not testing the code properly? I mean the linter is supposed to show error for `;` in this project.

**Comment by jameslinimk** [comment]
> You should add custom query support too. Also, I don't think you'd need to `resolve(undefined)`... `resolve()` should resolve `undefined` by default no? 🤔 Also, I see you are not testing the code properly? I mean the linter is supposed to show error for `;` in this project.

Yeah sorry, I was gonna test later. And good ideas

**Comment by hands8142** [comment]
Please erase console.log

**Comment by jameslinimk** [comment]
> Please erase console.log

Done

**Review by Snowflake107 — CHANGES_REQUESTED** [review]
I dont think you need to do this:

```js
const gClient = (process.env.GENIUSAPI) ? new geniusLyrics.Client(process.env.GENIUSAPI) : new geniusLyrics.Client()
```

because by default, the api key parameter of `new geniusLyrics.Client()` would be `undefined` and `process.env.GENIUSAPI` returns `undefined` if there isn't `GENIUSAPI` in `process.env`. So using

```js
const gClient = new geniusLyrics.Client()
```

is fine.

**Comment by Snowflake107** [comment]
thanks for the PR, this feature is implemented in `rewrite` version in a different way 👍🏻

**Pull request closed without merging**
