### PR TITLE
Made a small fix

### PR DESCRIPTION
**Pull request by 3061LRTAGSPKJMORMRT**
Stops the big bulky error from stopping the bot

## Status

- [x] These changes have been tested and formatted properly.

### CODE REVIEW

**Review by Snowflake107 — CHANGES_REQUESTED** [review]
instead of
```js
{ message: "xx" }
```

we should use
```js
new Error("xx")
```

else it will conflict with typings

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Sure. Sorry not too great with ts. But yea, i tested it and it doesn't make that big fat error. The one that crashes the bot is if you leave the voice chat when there is more than 1 song in the queue

**Review by Snowflake107 — CHANGES_REQUESTED** [review]
hey could you add a `;`

**Comment by 3061LRTAGSPKJMORMRT** [comment]
sure

**Comment by 3061LRTAGSPKJMORMRT** [comment]
done!

**Comment by DevAndromeda** [comment]
this was implemented in #515 with better logic

**Pull request closed without merging**
