### PR TITLE
refactor(Player): make player generic

### PR DESCRIPTION
**Pull request by LOLBRUHNICE**
## Changes
Auto applies object type to queue.metadata when using createQueue, getQueue, deleteQueue, and the queue arg in the event from the type generic of Player Class

## Status

- [x] These changes have been tested and formatted properly.

### CODE REVIEW

**Comment by DevAndromeda** [comment]
I don't think this would work properly since `metadata` is assigned to each queue instance, not `Player`.

**Comment by LOLBRUHNICE** [comment]
I think that every user will just put same property and value into the queue metadata every time they create the queue

**Comment by DevAndromeda** [comment]
> I think that every user will just put same property and value into the queue metadata every time they create the queue

this would not be true always

**Comment by LOLBRUHNICE** [comment]
I changed something so that the user can also put something into metadata that isn't defined in the Player's Type Generic

**Comment by LOLBRUHNICE** [comment]
> I changed something so that the user can also put something into metadata that isn't defined in the Player's Type Generic

@DevAndromeda Is it ok?

**Comment by DevAndromeda** [comment]
@LOLBRUHNICE have you tested the code? I am expecting eslint errors here

**Comment by LOLBRUHNICE** [comment]
@DevAndromeda  can i turn off `@typescript-eslint/no-explicit-any` in .eslintrc.json to allow ```{[key: string]: any}``` type

**Pull request closed without merging**
