### PR TITLE
Added support for Apple Music

### PR DESCRIPTION
**Pull request by SiniMini876**
## Changes

I added a few types that refer to apple music, when the bot receives the Apple Music URL (through the `search` method in `Player` class) it goes to a number of processes to make sure if it's a song, album, or playlist. From there I fetch the URL using `axios` and cheerio and get the track/album/playlist data. The data includes a number of properties but the most important one is the track title. We use the title as a query for the youtube bridge using the youtube-sr. After I call the search function in `youtube-sr` the bot receives all of the information needed to play the track/album/playlist.

## Status

- [ ✅] These changes have been tested and formatted properly.
- [❌ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

### CODE REVIEW

**Comment by DevAndromeda** [comment]
Thank you for the contribution but we have decided to not include any other extractors directly into discord-player. This update should go into **[@discord-player/extractor](https://github.com/discord-player/extractor)** instead

**Comment by SiniMini876** [comment]
> Thank you for the contribution but we have decided to not include any other extractors directly into discord-player. This update should go into **[@discord-player/extractor](https://github.com/discord-player/extractor)** instead

Thanks for your response. But wouldn't be more convenient to put it inside the main package?
The main package includes YouTube, Spotify, SoundCloud. And the missing one is Apple Music. Apple Music reached almost 100M users in 2021. I think you should think more about this...

Thanks

**Comment by DevAndromeda** [comment]
> > Thank you for the contribution but we have decided to not include any other extractors directly into discord-player. This update should go into **[@discord-player/extractor](https://github.com/discord-player/extractor)** instead
> 
> Thanks for your response. But wouldn't be more convenient to put it inside the main package? The main package includes YouTube, Spotify, SoundCloud. And the missing one is Apple Music. Apple Music reached almost 100M users in 2021. I think you should think more about this...
> 
> Thanks

main package does include youtube but the extractors are not built into the main package itself. It uses external packages for them. Also, we did include some extractors in the main package before but it created some problems so we decided to split the extractors to **[@discord-player/extractor](https://github.com/discord-player/extractor)**

**Comment by SiniMini876** [comment]
> > > Thank you for the contribution but we have decided to not include any other extractors directly into discord-player. This update should go into **[@discord-player/extractor](https://github.com/discord-player/extractor)** instead
> > 
> > 
> > Thanks for your response. But wouldn't be more convenient to put it inside the main package? The main package includes YouTube, Spotify, SoundCloud. And the missing one is Apple Music. Apple Music reached almost 100M users in 2021. I think you should think more about this...
> > Thanks
> 
> main package does include youtube but the extractors are not built into the main package itself. It uses external packages for them. Also, we did include some extractors in the main package before but it created some problems so we decided to split the extractors to **[@discord-player/extractor](https://github.com/discord-player/extractor)**

So you're saying that the main package used to include extractors but now every extractor that you want to add has to be in the @discord-player/extractors? 
I get it, but it doesn't interfere with any of the code inside the package. So I don't understand why should we add another step for beginners to use the package for streaming audio.

**Comment by DevAndromeda** [comment]
Yeah the current implementation for extractors is very limited, as you are unable to interact with core api. There's a discussion open for the future of this library with new and better features. If you have any suggestions, feel free to share it there.

Discussion: https://github.com/Androz2091/discord-player/discussions/989

**Comment by SiniMini876** [comment]
> Yeah the current implementation for extractors is very limited, as you are unable to interact with core api. There's a discussion open for the future of this library with new and better features. If you have any suggestions, feel free to share it there.
> 
> Discussion: #989

I get it. The future plans are to move all of the built-in extractors to the [@discord-player/extractors](https://github.com/discord-player/extractor)? if it is then I will be happy to help with the migration.

**Comment by DevAndromeda** [comment]
> > Yeah the current implementation for extractors is very limited, as you are unable to interact with core api. There's a discussion open for the future of this library with new and better features. If you have any suggestions, feel free to share it there.
> > Discussion: #989
> 
> I get it. The future plans are to move all of the built-in extractors to the [@discord-player/extractors](https://github.com/discord-player/extractor)? if it is then I will be happy to help with the implementation.

Yeah it is.

**Comment by SiniMini876** [comment]
> > > Yeah the current implementation for extractors is very limited, as you are unable to interact with core api. There's a discussion open for the future of this library with new and better features. If you have any suggestions, feel free to share it there.
> > > Discussion: #989
> > 
> > 
> > I get it. The future plans are to move all of the built-in extractors to the [@discord-player/extractors](https://github.com/discord-player/extractor)? if it is then I will be happy to help with the implementation.
> 
> Yeah it is.

Check out the [PH](https://github.com/discord-player/extractor/pull/12) on the [@discord-player/extractors](https://github.com/discord-player/extractor).

**Comment by DevAndromeda** [comment]
Adding more and more extractors/streaming api to discord-player's core is making it heavy and having to maintain all those sources is a nightmare. IMO, moving all of these stuff to userland will be a better idea. You can open an issue or make a pr to list your extractor(s) in discord-player.

**Pull request closed without merging**
