### PR TITLE
⚡ TypeScript Rewrite

### PR DESCRIPTION
**Pull request by Snowflake107**
# This PR includes
- Complete TypeScript rewrite
- Custom Extractors API
- Some bug fixes
- No breaking changes

### CODE REVIEW

**Review by Androz2091 — COMMENTED** [review]
Looks awesome! 😎 
Thank you so much for this update 👍 

One small thing : I think we should not add @discord-player/extractors to the dependencies. Users should only install it if they need to use them. And this would allow us to release new @discord-player/extractors version without the need of bumping the version in the discord-player package.json file. What do you think?

**Comment by Snowflake107** [comment]
> Looks awesome! 😎
> Thank you so much for this update 👍
> 
> One small thing : I think we should not add @discord-player/extractors to the dependencies. Users should only install it if they need to use them. And this would allow us to release new @discord-player/extractors version without the need of bumping the version in the discord-player package.json file. What do you think?
> Otherwise, I don't see the point of making a separate package

done 👍

**Comment by Androz2091** [comment]
Perfect, I will review the PR as soon as possible! 👍 
Thanks again

**Comment by Androz2091** [comment]
How are errors handled now?

**Review by Androz2091 — CHANGES_REQUESTED** [review]
The documentation is entirely broken

**Comment by Snowflake107** [comment]
also closes #361

**Pull request merged**
