### PR TITLE
✨New player features

### PR DESCRIPTION
**Pull request by Snowflake107**
# Extractor Progress
- [x] Facebook Extractor
- [x] Discord Extractor
- [x] Vimeo Extractor

### CODE REVIEW

**Comment by Snowflake107** [comment]
Discord Extractor should be able to extract anything similar to discord attachments

**Comment by Snowflake107** [comment]
**New Events**
- `playlistParseStart`: Emitted whenever player starts parsing playlist contents (mostly soundcloud)
- `playlistParseEnd`: Emitted whenever player finishes parsing playlist contents (mostly soundcloud)

Both of them have `2` parameters: `Playlist/Raw Playlist`, `DiscordMessage`:

```js
player.on("playlistParseStart", (data, message) => {
    message.channel.send("Started parsing playlist!");
})

player.on("playlistParseEnd", (data, message) => {
    message.channel.send("Finished parsing playlist!");
})

```

**Review by ToledoSDL — APPROVED** [review]

**Comment by Snowflake107** [comment]
**setPosition example**

```js
const time = parseInt(args[0]); // parse time as int

client.player.setPosition(message, time * 1000); // we need time in ms
```

> Expected: Track re-plays from the specified time/position.

**Comment by Snowflake107** [comment]
**Extractors Implemented**
- [x] Facebook
- [x] Vimeo
- [ ] Discord

**Comment by Androz2091** [comment]
I'm testing it, it looks great!!

**Comment by Androz2091** [comment]
Discord Extractor : tested, but as `durationMS` is not defined, we can't use the progress bar 🤔

**Comment by Androz2091** [comment]
Soundcloud Extractor : tested ✅

**Comment by Androz2091** [comment]
Facebook Extractor : doesn't work with the tested videos : 
`-` https://www.facebook.com/discord/videos/457696585410264
`-` https://www.facebook.com/Creapills/videos/votre-cerveau-ne-va-pas-appr%C3%A9cier-cette-vid%C3%A9o/1997853370246007/

**Comment by Androz2091** [comment]
Vimeo Extractor : tested ✅ (`description` is null, but I think there is no way to get it?)

**Comment by Snowflake107** [comment]
> Vimeo Extractor : tested ✅ (`description` is null, but I think there is no way to get it?)

We are extracting from `https://player.vimeo.com/video/VIDEO_ID`, unfortunately there isn't any `video description`.

**Comment by Androz2091** [comment]
> > Vimeo Extractor : tested ✅ (`description` is null, but I think there is no way to get it?)
> 
> We are extracting from `https://player.vimeo.com/video/VIDEO_ID`, unfortunately there isn't any `video description`.

All right, no problem I understand

The problem concerning the attachment file that brokes the progress bar (as there is no durationMS property) is a little bit annoying. Anyway if no solution can be found we will let it empty...

**Comment by Androz2091** [comment]
And what about Facebook? Are the example links I sent working for you?

**Comment by Snowflake107** [comment]
@Androz2091 yeah looks like we need to improve facebook

**Comment by Androz2091** [comment]
Okay, tell me when it's fixed

**Review by ToledoSDL — APPROVED** [review]

**Review by ToledoSDL — APPROVED** [review]

**Review by ToledoSDL — APPROVED** [review]

**Review by Androz2091 — APPROVED** [review]

**Comment by Androz2091** [comment]
Thank you 👍

**Pull request merged**
